// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            LivroClienteEmprestimo = new HashSet<LivroClienteEmprestimo>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("cliCPF")]
        [StringLength(14)]
        public string CliCpf { get; set; }
        [Column("cliNome")]
        [StringLength(100)]
        public string CliNome { get; set; }
        [Column("cliEndereco")]
        [StringLength(50)]
        public string CliEndereco { get; set; }
        [Column("cliCidade")]
        [StringLength(50)]
        public string CliCidade { get; set; }
        [Column("cliBairro")]
        [StringLength(50)]
        public string CliBairro { get; set; }
        [Column("cliNumero")]
        [StringLength(14)]
        public string CliNumero { get; set; }
        [Column("cliTelefoneCelular")]
        [MaxLength(14)]
        public byte[] CliTelefoneCelular { get; set; }
        [Column("cliTelefoneFixo")]
        [MaxLength(13)]
        public byte[] CliTelefoneFixo { get; set; }

        [InverseProperty("LceIdLivroNavigation")]
        public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; }
    }
}