// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models
{
    //[Keyless]
    public partial class VwLivroClienteEmprestimo
    {
        [Required]
        [Column("cliCPF")]
        [StringLength(14)]
        public string CliCpf { get; set; }
        [Required]
        [Column("cliNome")]
        [StringLength(100)]
        public string CliNome { get; set; }
        [Required]
        [StringLength(50)]
        public string LivroNome { get; set; }
        [Column("id")]
        public int Id { get; set; }
        public int LceIdLivro { get; set; }
        public int LceIdCliente { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LcedataEmprestimo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LcedataEntrega { get; set; }
        public bool LceEntregue { get; set; }
    }
}